version: '3'

services:
  ctf01d_db:
    image: mysql:5.7
    volumes:
      - "./dckr_mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KzhyntJxwt
      MYSQL_DATABASE: ctf01d
      MYSQL_USER: ctf01d
      MYSQL_PASSWORD: ctf01d
    networks:
      - ctf01d_net

  ctf01d_jury:
    build: ../
    depends_on:
      - ctf01d_db
    image: sea5kg/ctf01d:debug
    environment:
      CTF01D_WORKDIR: "/usr/share/ctfd01d/data"
    volumes:
      - "./data_sample:/usr/share/ctfd01d/data"
    ports:
      - "8080:8080"
    restart: always
    links:
      - "ctf01d_db"
    networks:
      - ctf01d_net

networks:
  ctf01d_net:
    driver: bridge
        
