language: cpp

branches:
  only:
    - master

dist: bionic

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - default-libmysqlclient-dev
    - pkg-config
    - libcurl4-openssl-dev
    - zlibc
    - zlib1g
    - zlib1g-dev
    - libpng-dev

# Build steps
script:
  - ./clean.sh
  - ./build_simple.sh
