language: cpp

os:
  - linux

branches:
  only:
    - master

matrix:
  include:
    - dist: bionic

services:
  - mysql

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - default-libmysqlclient-dev
    - pkg-config
    - libcurl4-openssl-dev
    - zlibc
    - zlib1g
    - zlib1g-dev
    - libpng-dev
    - python3-pip

# Install dependencies
before_install:
  - sudo apt-get update -qq
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `ctf01d` CHARACTER SET utf8 COLLATE utf8_general_ci;'

# Build steps
script:
  - ./run_travis.sh
  